#ENC[AES256_GCM,data:z3WVi6xNsovVFQm5pAudgoMYd0z4+q3q59b8jUNhKh6+qxTdeQa/2gem2R+CjuuNk32B7LTiWgamh2zPNPVimUjIL2xlRVxvC7v/cV79/zpGGy1ggrP0flcxP7dNO0oWjJpXjagHq4rNO9IvbBsHhmlYPGmws4Y7OgNRgAv6sIm1,iv:OKKYrRLLDxtteg97wMKQ/6+w5QZHJOzbYlIG7cwTnY8=,tag:t8Ni4W5X3/mk1Juc52Yqzg==,type:comment]
#ENC[AES256_GCM,data:t7gjXOkgwsvpb/DIK1B67zFuxm+K/Z0ZNtzwtYXLVlfMBoDsnCdIGx4ZHgk16zmfTh8a/xMmynWr/QTqLA==,iv:DeLfX2cA2Qu6mzyGMk+8e0j6SAvJ+Fz9pHT5i7NuNHw=,tag:+/Wrz/4OBpLgyXyh9B5i8w==,type:comment]
#ENC[AES256_GCM,data:JOU5fo8w4567+cvJe7l+J5+ER5if+UYT/CacZ58eScIhN8s93A==,iv:vzrZVVFeh3IqHw445poSNLLFA9gBoydMMfjW+Js8FAA=,tag:Icv148lNC4Aoa9QDzmJZiA==,type:comment]
#
#ENC[AES256_GCM,data:b8EBYrwLPyxoazZSsLSxh9VjwjJdoq9AqFTF6EZUa+DWVH/yFlcoKJ7cDXmy1RwbWG1WH2WEsoEraSJRfe90GIRVx95hireQzCo89Oh5o8mMChsN29ZrlO2STa1t0ivYiQ==,iv:wFdQUBTBHEbs7wp0of+0XPWwGoUiDvAgaM7qJmjszRc=,tag:7B/ZRNEsRkMC9MUlPMkIjQ==,type:comment]
#ENC[AES256_GCM,data:Fdc/5XicmXBZvQzZzJ29dVN200j/Vv9lmePyqLlSve53MUJFBIf4BB0xlfjg4e1VrBpolxKqDQDRzJrjxHYsK0EpYb20B1Tz00/OwGBjt1LZgaCRFv7zoxgyBo2/iW0PA4d7MP07e1PBLyScZzQMb0Y6A2CoZGIoWbwRZnUeVW9nxQ==,iv:hVEqoFSaoKtNPsG7wyodu5L42wC/2TbHKCNscetFxSg=,tag:ydhFdHFCFspt1b8ocXueLA==,type:comment]
#ENC[AES256_GCM,data:Xh2LngmjlU6wu4kj/S+0bRkfWbW1optiv8bN35Em9Q==,iv:Il291qULt0CKvxjE+1KFxKWCGSLew5fZTdCqK+B6RME=,tag:wjsia2czZPqdjGUT8Nh8eg==,type:comment]
secrets:
    DB_USER: ENC[AES256_GCM,data:oMtOPQ==,iv:HJeRuHvS+58H8BmJ5zg7p3BAwzV4qDbT6J59G1+HCZA=,tag:hgy1j4j7mHmYe8up/lIgTQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:qgWmukzDpFNYLbHG,iv:Uqq3RI+ONDKO8w301sP4dWhkisQOKvGWXH5Lcl4gT5Y=,tag:lB5ywSrAgLELRRj+xf1few==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MXRsZVIrNGlhTVpzNTRZ
            T3dJd3BDS01MS0RMSVByNk80TGk4RnAreWhRCkRhTUp4cHYydlI3QWc1U3daRHh2
            YUhqT3BISWlUVzVmQ1IxeHZPcXBNcEUKLS0tIDRqanZLbzJBU3FGVU5qR05FenRZ
            ZkJzNG9pSnVodklYOUY2bEpMWVB3L1EKiRR2T/i+DscyM+TU+Rp8lRai9k3MYnye
            tLyEGRJdkoed0qT96ZhsKIyPeP8cEKP1bRLenNzIEazJZ/z3TQ9l9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p7tv5dgg2qn9vm5gujpxg8qn4u0502ctzxa4637zrdmw6cwc89mqa8vz93
    lastmodified: "2026-08-16T19:35:16Z"
    mac: ENC[AES256_GCM,data:qL2BWQIvahtvwlTrRjqPKadHfZRHNcOyYo3W/Yazdn7BRSHGeCO4swRck/cQT97vX8MWaHZgzDYSMEAeHPC5LDEer0VZsYfHXEFKXUoT486rkmf9Z0QwFteXq5tB6tWCiud1uzYXL+ieIpTXURb/xe+yfj/lgwzFoKeM3LuzqTg=,iv:wYnHdMUJNuJ2SSn8yhmuzQ8VBETG1MQrbAOafBuVXu0=,tag:ocMinUtlb3+oYBrFMzwpYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
