#ENC[AES256_GCM,data:/LYOyLGKZxcEs9qrXtL4+G2IljegaknCFjGxrAIXt97R/dIMEBWJkivnpLiN9r+Y+RQHO/C28QvJkLxlCqZkSdfWKEFEQRPB1yh3U5bzSFE/05wHVlXC8xOxIN6SQmrIRbfGMHgXHPB0hjNmL1ZwKBpVmk7I9iTklHMrv9aOEHY=,iv:+P+mryy0Re3GXUU+RiUjooGCxkf8iudj9BVZQvmT9U4=,tag:5HJFPxUCPKWuf5JKbpLVHg==,type:comment]
#ENC[AES256_GCM,data:L8CnR1V0w8Wladk7CK2z5mdYzQQs5YVTYTiCypWJ/IocniMDq0frKP7Sih1dcIT64NTHWHkS5BiSDmAi4wfj8V1NsuSqpgjCtsqwb4T6oXXEk/QkHO5hGBYX5ioT58PeDwHDD+hZLgdm/X0E9UkrUMkPM4WHf5gX,iv:7a6dgSKnT5JyfPp1jY1kkYjxU8eulgNFqq8wX+Zrjkw=,tag:/NBV6l1CcYmOWM+nlJ79pg==,type:comment]
#
#ENC[AES256_GCM,data:202t/2+OPJqODoxHkXdDbMLn50lfKlEx60T1vCMOnKoLkdpPZRMNcSjmbqZiMFLnaAZcHMEyiMEQ1w7lCSR0vwVMYA==,iv:e3JbuYuHwUhLx4Qk6PsU77+e9Js4dOZK3B3uTiL4SaE=,tag:bUVzJLPKIEe2IVvSkqtFbg==,type:comment]
#ENC[AES256_GCM,data:Z6VMJtr+MUIEO4RQKcx51vEHWdcNKooge9HOilj+7LhPfTpRvlL83w==,iv:HeprcWWNjYPw912BsHUJ72R/WYLQ5ZOSdBk7dDQJh4E=,tag:vvFBYfrwBs94bRd/VfQHIg==,type:comment]
#
#ENC[AES256_GCM,data:U3L6lLkICHAMRoeoxDGzI4edc7WcE1n8FpJ4IqiPxjAjZ/SwKYonqgieTSd1WwuhiftcwpLBzOADzDvP17lYupkY9C+eOGAjmmb1s75N5t0tOhH2CJ0Or5yRU+uDAYcpR7rIzJSGa0BFZ5lY8/nCspGKjkvb,iv:wO/UjOgcpGlVgU1M04Gl7ecocNTBlhOWBo8TJl38omA=,tag:T23CbYbdcgyqaSx16HSuHw==,type:comment]
#ENC[AES256_GCM,data:o5A9Htm1a8JOygrzIW5GHYlC2Tuwp9Z6VB11lymQaLTMpCrG5hQROrt6Ba/Qsz5F5cL9FYFtlZ4S6aMf5nHbGPPo+7fKzagzFZ+ZY7TcYPL/GxxOOELUxSG2oTbtc47XCxxIw21uqvu8/SnBgJYziK0Lbf2Je+/c3dAgsJrKVpfpuI2kDEABsZSDwbEwpYQpwFIIjAo=,iv:abr7ZJKh6CzYRa0Y06o8QtzC/rnB2d2yWswOrSyQsK8=,tag:l4WBvJHzWBKroktL30XEOw==,type:comment]
secret:
    dbUser: ENC[AES256_GCM,data:VRspfg==,iv:YzMUT29qJBrah9TAaXXh/7Q+QinB7Knt2S/mDRzCzg4=,tag:bcg3N5UMJ9b66APZOEBG8Q==,type:str]
    dbPassword: ENC[AES256_GCM,data:8dMw/mEqnMu7/QTi,iv:h5ahs7sxJziJKpi3N14UTS+73FOWr+WQ5qqq6TvI9HI=,tag:/QYhTVI4hrxmatUMhbdaig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpT3NacXJnZ3lWRXNiclVB
            NDJIaDRHS3lCZzlVSTlseThuYkxCQ2grNkg0CkFJbUx5amR2Q3NGd3E0RCtrZHND
            VmJML29nb05hUStuVktVdHF0L2pDd0EKLS0tIHNXekZoY05TREVxbkdnQkpLd2p4
            cEk1eldiNHRIU3FkT1hUcytLNkRHeXMKFwgXpgRFaJzUuPCqQC8KgOloXjJzbanM
            eSsIrm/cUgCxhbcCzrhKAcbF+9dpDsuWqxk5hmxIE4Iqnag/cBRuoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p7tv5dgg2qn9vm5gujpxg8qn4u0502ctzxa4637zrdmw6cwc89mqa8vz93
    lastmodified: "2026-08-16T19:33:35Z"
    mac: ENC[AES256_GCM,data:gCXjNRSwX+1nP9yy0WDq9zmZ0OkhRZcIPGTXv0Csluil9XfnGszaYfvk5jAdwtWMJVzfU6uhzYLgP4lXgjWqBJ+D4prwS+g+1GnGu09SSqDreCWEhUmIw3cYkSP9bTjKNC5u2BGKNwSyZOn9GgK9E2kRZntRHqpxNbUYxSHQMn4=,iv:Y5QOw5/iDIDEy5ElD7Jinm6lpoKhb5H3Pf2U8NMG3Kg=,tag:Ybsm3Le0ZMmQ0gNe6Kqfyw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
